// Each puzzle's three categories look unrelated — they're only linked by targetWord.
// cat1Words / cat2Words / cat3Words are used for client-side "which circle does this guess fit?"
// grading so players get a placement hint without needing an API key.

const puzzles = [
  {
    id: 1,
    targetWord: "MERCURY",
    category1: "Closest to the Sun",
    category2: "Freddie ___ (Queen)",
    category3: "Thermometer Liquid",
    cat1Words: ["venus","mars","earth","planet","solar","orbit","nasa","space","saturn","jupiter","neptune","pluto","asteroid","comet","sun"],
    cat2Words: ["freddie","queen","bowie","jagger","rock","bohemian","music","singer","band","guitarist","mick","zeppelin","led","lennon","brian"],
    cat3Words: ["silver","temperature","thermometer","liquid","metal","tin","zinc","celsius","fever","barometer","aluminum","lead","fluid","temp"],
  },
  {
    id: 2,
    targetWord: "RING",
    category1: "Saturn's Feature",
    category2: "Boxing Venue",
    category3: "Tolkien's Precious",
    cat1Words: ["saturn","planet","orbit","space","ice","cosmic","gas","celestial","moon","solar","cassini","uranus","halo"],
    cat2Words: ["boxing","fight","ropes","boxer","round","knockout","punch","referee","corner","belt","wrestling","bout","heavyweight"],
    cat3Words: ["tolkien","hobbit","lord","precious","frodo","gandalf","mordor","shire","gollum","sauron","elvish","quest","one","bilbo"],
  },
  {
    id: 3,
    targetWord: "JACK",
    category1: "Captain ___ Sparrow",
    category2: "Car Lifting Tool",
    category3: "Below Queen in Cards",
    cat1Words: ["pirate","sparrow","depp","ship","caribbean","treasure","blackbeard","captain","rum","davy","jones","skull"],
    cat2Words: ["car","tire","wheel","mechanic","garage","wrench","hydraulic","lift","flat","vehicle","lug","nut","screwdriver"],
    cat3Words: ["cards","deck","queen","ace","king","ten","playing","poker","blackjack","hearts","spades","clubs","diamonds","shuffle"],
  },
  {
    id: 4,
    targetWord: "IRON",
    category1: "Tony Stark's Alias",
    category2: "Removes Shirt Creases",
    category3: "Blood Needs It",
    cat1Words: ["stark","avenger","marvel","armor","suit","hero","superhero","pepper","tony","shield","jarvis","arc","reactor","war"],
    cat2Words: ["shirt","laundry","wrinkle","crease","steam","clothes","fabric","press","board","garment","textile","smooth","flat"],
    cat3Words: ["blood","anemia","hemoglobin","vitamin","mineral","supplement","spinach","health","nutrition","red","cells","oxygen","deficiency"],
  },
  {
    id: 5,
    targetWord: "DIAMOND",
    category1: "Baseball's Infield",
    category2: "April Birthstone",
    category3: "Neil ___ (Sweet Caroline)",
    cat1Words: ["baseball","infield","pitcher","batter","base","shortstop","mound","plate","stadium","home","run","foul","hardball","softball"],
    cat2Words: ["birthstone","gem","april","jewelry","necklace","jewel","precious","stone","sapphire","ruby","emerald","crystal","gem"],
    cat3Words: ["neil","sweet","caroline","singer","song","songwriter","folk","pop","acoustic","cherry","cracklin","rosie","music"],
  },
  {
    id: 6,
    targetWord: "CROWN",
    category1: "Netflix Royal Drama",
    category2: "Dentist's Tooth Cap",
    category3: "Monarch's Headwear",
    cat1Words: ["netflix","royal","elizabeth","drama","series","show","monarchy","palace","reign","binge","watch","philip","margaret","streaming"],
    cat2Words: ["dentist","tooth","dental","enamel","molar","cap","cavity","filling","bridge","implant","oral","porcelain","root","canal"],
    cat3Words: ["monarch","king","queen","royal","throne","scepter","jewel","tiara","emperor","coronation","kneel","noble","regal"],
  },
  {
    id: 7,
    targetWord: "PILOT",
    category1: "Flies the Plane",
    category2: "TV Show's First Episode",
    category3: "Ballpoint Pen Brand",
    cat1Words: ["plane","aircraft","cockpit","aviation","airline","flight","copilot","captain","altitude","takeoff","landing","runway","air"],
    cat2Words: ["show","episode","series","premiere","television","tv","network","season","debut","sitcom","spinoff","broadcast","cast"],
    cat3Words: ["pen","ballpoint","ink","write","bic","sharpie","marker","rollerball","fountain","gel","stationary","office","refill"],
  },
  {
    id: 8,
    targetWord: "HOOK",
    category1: "Peter Pan's Villain",
    category2: "Song's Catchy Phrase",
    category3: "Fishing Essential",
    cat1Words: ["peter","pan","wendy","neverland","tinker","bell","pirate","lost","boys","crocodile","tick","tock","fairy","dust"],
    cat2Words: ["song","chorus","verse","lyric","catchy","music","refrain","bridge","pop","earworm","melody","riff","repeat","sing"],
    cat3Words: ["fish","fishing","line","bait","lure","rod","tackle","catch","cast","worm","fly","reel","angler","trout"],
  },
  {
    id: 9,
    targetWord: "SCALES",
    category1: "Symbol of Justice",
    category2: "Fish's Skin Layer",
    category3: "Measures Your Weight",
    cat1Words: ["justice","law","court","judge","lawyer","balance","legal","verdict","blind","libra","courthouse","gavel","trial","roman"],
    cat2Words: ["fish","skin","carp","salmon","trout","fin","gill","underwater","sea","aquatic","cod","bass","perch","herring"],
    cat3Words: ["weight","bathroom","pound","kilogram","bmi","diet","measure","gym","body","digital","analog","floor","mass","fat"],
  },
  {
    id: 10,
    targetWord: "TRUNK",
    category1: "Elephant's Nose",
    category2: "Car's Rear Storage",
    category3: "Men's Swimwear",
    cat1Words: ["elephant","tusk","ivory","africa","savanna","proboscis","mammal","zoo","peanut","herd","poach","ivory","large"],
    cat2Words: ["car","luggage","suitcase","storage","boot","rear","travel","bag","vehicle","roadtrip","hatch","spare","tire"],
    cat3Words: ["swim","shorts","swimsuit","pool","beach","boxer","underwear","brief","speedo","bathing","summer","resort","trunks"],
  },
  {
    id: 11,
    targetWord: "BANK",
    category1: "Holds Your Savings",
    category2: "River's Edge",
    category3: "Pilot's Turn Move",
    cat1Words: ["money","savings","account","deposit","loan","mortgage","atm","finance","interest","vault","teller","check","invest"],
    cat2Words: ["river","stream","creek","shore","edge","water","canal","flood","clay","muddy","current","tributary","overflow"],
    cat3Words: ["airplane","plane","turn","maneuver","fly","pilot","tilt","roll","aviation","wing","steep","approach","attitude"],
  },
  {
    id: 12,
    targetWord: "CRANE",
    category1: "Construction Site Lifter",
    category2: "Origami Paper Art",
    category3: "Wading Bird",
    cat1Words: ["construction","site","beam","steel","hoist","tower","building","hard","hat","scaffold","operator","cable","load"],
    cat2Words: ["origami","paper","fold","japanese","japan","thousand","wish","art","tradition","swan","star","lotus","crease"],
    cat3Words: ["bird","wading","heron","stork","flamingo","feather","marsh","wetland","tall","grey","sandhill","whooping","waterfowl"],
  },
  {
    id: 13,
    targetWord: "PITCHER",
    category1: "Baseball's Mound Role",
    category2: "Holds the Lemonade",
    category3: "Bug-Eating Plant",
    cat1Words: ["baseball","mound","ball","batter","catcher","fastball","slider","strikeout","windup","bullpen","rotation","relief","ace"],
    cat2Words: ["lemonade","water","juice","jug","pour","glass","beverage","kool","drink","iced","tea","container","carafe"],
    cat3Words: ["carnivorous","plant","venus","flytrap","sundew","insect","bug","trap","digest","bog","nepenthes","enzyme","nitrogen"],
  },
  {
    id: 14,
    targetWord: "NEEDLE",
    category1: "Thread Goes Through It",
    category2: "Vinyl Record's Tip",
    category3: "Cleopatra's Obelisk",
    cat1Words: ["thread","sewing","stitch","sew","fabric","embroidery","knit","yarn","thimble","darn","hemming","bobbin","quilt"],
    cat2Words: ["vinyl","record","turntable","stylus","play","music","groove","phonograph","spin","lp","album","analog","cartridge"],
    cat3Words: ["cleopatra","egypt","obelisk","ancient","monument","hieroglyph","pharaoh","cairo","london","new","york","paris","stone"],
  },
  {
    id: 15,
    targetWord: "BOLT",
    category1: "Usain ___ Sprinter",
    category2: "Screws Into a Nut",
    category3: "Locks the Door",
    cat1Words: ["usain","sprint","olympic","runner","track","fastest","jamaica","athletics","hundred","meters","gold","medal","world","record"],
    cat2Words: ["nut","screw","fastener","hardware","wrench","torque","thread","metal","washer","tighten","loosen","hex","allen"],
    cat3Words: ["door","lock","latch","security","deadbolt","key","slide","bar","chain","safety","padlock","mechanism","handle"],
  },
  {
    id: 16,
    targetWord: "CARDINAL",
    category1: "Vatican Official",
    category2: "St. Louis MLB Team",
    category3: "Red Backyard Bird",
    cat1Words: ["catholic","church","pope","vatican","bishop","priest","clergy","roman","conclave","papal","holy","see","rome","faith"],
    cat2Words: ["baseball","st","louis","mlb","team","redbirds","league","stadium","national","serie","cards","bat","field"],
    cat3Words: ["bird","red","feeder","robin","finch","sparrow","beak","winter","backyard","crest","songbird","male","perch"],
  },
  {
    id: 17,
    targetWord: "SPRING",
    category1: "Season After Winter",
    category2: "Mattress Inner Coil",
    category3: "Natural Water Source",
    cat1Words: ["winter","summer","fall","autumn","season","warm","bloom","april","flower","march","pollen","equinox","thaw","blossom"],
    cat2Words: ["coil","mattress","bed","metal","bounce","elastic","compress","wire","foam","pocket","tempur","innerspring","tension"],
    cat3Words: ["water","source","evian","well","mineral","fresh","underground","aquifer","geyser","hot","thermal","bubbling","natural"],
  },
  {
    id: 18,
    targetWord: "MOUSE",
    category1: "Computer's Clicker",
    category2: "Mickey's Partner",
    category3: "Cheese-Loving Pest",
    cat1Words: ["computer","cursor","click","keyboard","peripheral","device","usb","scroll","pointer","touchpad","wireless","bluetooth","pc"],
    cat2Words: ["minnie","disney","mickey","cartoon","animation","character","club","orlando","theme","park","ears","gloves","magic"],
    cat3Words: ["rat","rodent","cheese","pest","trap","squeaky","furry","nibble","gnaw","infestation","attic","barn","scurry"],
  },
  {
    id: 19,
    targetWord: "STRIKE",
    category1: "Bowling's Perfect Roll",
    category2: "Workers Walk Out",
    category3: "Baseball Out Called",
    cat1Words: ["bowling","pin","spare","gutter","lane","ball","perfect","alley","turkey","pocket","ten","frame","approach"],
    cat2Words: ["worker","labor","union","protest","picket","walkout","demand","wage","factory","rally","bargain","collective","action"],
    cat3Words: ["baseball","swing","out","batter","three","umpire","called","pitcher","inning","plate","foul","count","strikeout"],
  },
  {
    id: 20,
    targetWord: "KNIGHT",
    category1: "Chess's Horse Piece",
    category2: "Sir Paul's Title",
    category3: "Medieval Armored Warrior",
    cat1Words: ["chess","piece","horse","move","bishop","rook","pawn","queen","checkmate","fork","board","gambit","opening"],
    cat2Words: ["paul","mccartney","beatles","sir","knighthood","britain","honor","obe","mbe","royal","queen","buckingham","palace"],
    cat3Words: ["medieval","armor","sword","shield","castle","joust","squire","crusade","lance","helm","chivalry","quest","damsel"],
  },
  {
    id: 21,
    targetWord: "POOL",
    category1: "Billiards Table Game",
    category2: "Carpool's First Half",
    category3: "Summer Swim Spot",
    cat1Words: ["billiards","cue","ball","eight","snooker","rack","pocket","chalk","break","hustle","table","felt","triangle"],
    cat2Words: ["carpool","commute","share","ride","coworker","traffic","vehicle","driver","rideshare","uber","vanpool","highway"],
    cat3Words: ["swim","water","chlorine","lane","splash","dive","lifeguard","towel","backyard","resort","lap","float","cannonball"],
  },
  {
    id: 22,
    targetWord: "BRIDGE",
    category1: "Card Game for Four",
    category2: "Dentist's Tooth Fix",
    category3: "Spans a River",
    cat1Words: ["cards","four","players","trump","bid","suit","partner","whist","trick","hand","dummy","auction","contract"],
    cat2Words: ["dentist","tooth","dental","implant","crown","gap","prosthetic","oral","porcelain","false","missing","root","canal"],
    cat3Words: ["river","crossing","span","arch","suspension","engineering","traffic","golden","gate","brooklyn","cable","stayed","beam"],
  },
  {
    id: 23,
    targetWord: "DRAFT",
    category1: "Unsent Email Status",
    category2: "NFL Rookie Selection",
    category3: "Beer From the Tap",
    cat1Words: ["email","unsent","folder","inbox","compose","message","outlook","gmail","mailbox","send","save","write","attachment"],
    cat2Words: ["nfl","football","pick","selection","prospect","rookie","team","league","combine","quarterback","round","bust","bust"],
    cat3Words: ["beer","tap","pub","keg","lager","ale","brewery","pint","bartender","draught","craft","handle","pour"],
  },
  {
    id: 24,
    targetWord: "CROW",
    category1: "Jim ___ Laws",
    category2: "Black Noisy Bird",
    category3: "To Brag Loudly",
    cat1Words: ["jim","segregation","racism","south","civil","rights","discrimination","era","reconstruction","plantation","jim","apartheid"],
    cat2Words: ["raven","rook","jackdaw","magpie","blackbird","feather","flock","murder","corvid","dark","caw","noisy","perch"],
    cat3Words: ["brag","boast","gloat","proud","show","arrogant","swagger","strut","preen","vaunt","rooster","cocky","taunt"],
  },
  {
    id: 25,
    targetWord: "STAMP",
    category1: "Postage on Letters",
    category2: "Rubber Office Seal",
    category3: "Stomp Your Foot",
    cat1Words: ["postage","mail","letter","envelope","post","office","send","usps","collect","philately","lick","afffix","airmail"],
    cat2Words: ["rubber","approve","office","ink","mark","seal","official","pad","approve","notary","certified","bureaucracy"],
    cat3Words: ["stomp","foot","floor","dance","march","tap","ground","tantrum","anger","boot","heel","fury","pound"],
  },
  {
    id: 26,
    targetWord: "NET",
    category1: "Tennis Court Divider",
    category2: "Income After Tax",
    category3: "Fisherman's Trap",
    cat1Words: ["tennis","court","serve","rally","volley","wimbledon","shot","match","badminton","ping","pong","polo","shuttlecock"],
    cat2Words: ["income","tax","salary","gross","profit","earnings","revenue","deduction","take","home","pay","withholding","w2"],
    cat3Words: ["fish","catch","trawl","trap","haul","ocean","shrimp","lobster","cast","drag","seine","mesh","gillnet"],
  },
  {
    id: 27,
    targetWord: "BEAR",
    category1: "Wall Street Pessimist",
    category2: "Winnie the Pooh's Kind",
    category3: "2nd Amendment Right",
    cat1Words: ["market","stocks","wall","street","trader","investor","decline","sell","finance","short","crash","pessimist","downturn"],
    cat2Words: ["winnie","pooh","honey","grizzly","panda","polar","kodiak","cub","woodland","teddy","koala","black","brown"],
    cat3Words: ["amendment","arms","constitution","second","gun","right","weapon","militia","carry","firearm","rifle","pistol","second"],
  },
  {
    id: 28,
    targetWord: "BLIND",
    category1: "Window Shade",
    category2: "Poker Forced Bet",
    category3: "Unbiased Wine Tasting",
    cat1Words: ["window","shade","venetian","roller","curtain","room","darkening","slat","shutter","drape","louvre","mini","panel"],
    cat2Words: ["poker","bet","small","big","chips","table","card","casino","ante","mandatory","pre","flop","forced"],
    cat3Words: ["wine","taste","sommelier","label","test","evaluation","judge","unbiased","tasting","comparison","double","objective"],
  },
  {
    id: 29,
    targetWord: "FLAME",
    category1: "Olympic Torch Carries It",
    category2: "Tinder's App Icon",
    category3: "Old ___ (Ex-Lover)",
    cat1Words: ["olympic","torch","relay","athens","ceremony","lit","paris","stadium","cauldron","greece","run","games","pass"],
    cat2Words: ["tinder","dating","swipe","app","match","icon","relationship","fire","emoji","hinge","bumble","swipe","right"],
    cat3Words: ["ex","lover","past","relationship","former","nostalgia","old","romance","rekindled","heartbreak","crush","flame","fling"],
  },
  {
    id: 30,
    targetWord: "CORAL",
    category1: "Reef Builder",
    category2: "Peachy-Pink Color",
    category3: "Venomous Snake Type",
    cat1Words: ["reef","ocean","sea","underwater","tropical","bleaching","fish","barrier","great","atoll","polyp","marine","scuba"],
    cat2Words: ["pink","orange","color","pastel","warm","hue","salmon","peach","blush","pantone","crayon","paint","terracotta"],
    cat3Words: ["snake","venomous","venom","reptile","king","mimic","florida","yellow","red","banded","herpetology","dangerous","moccasin"],
  },
];

export default puzzles;
